version: "3"
services:
  pg:
    image: sonatanfv/son-postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: sonata
      POSTGRES_DB: gatekeeper
      POSTGRES_USER: sonatatest
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
      
volumes:
  pg_data: 